### PR TITLE
Fix for movies not loading

### LINKED ISSUE #55: Videos Arent Loading Due to Case Sensitivity Issues
Videos arent loading because the language is "english" whereas the folder name is "English" (Data/English/Movies). The lowercase comes from `sprintf( localizedFilePath, VIDEO_LANG_PATH_FORMAT, GetRegistryLanguage().str(), pVideo->m_filename.str(), VIDEO_EXT );`

The case sensitivity logic on the std local file system does not seem to handle this deep folder path.

It's falling into this code and stopping:

```
if (pathFixedPart.empty())
			{
				// Required to allow creation of new files
				if (!(access & File::WRITE)) 
				{
					DEBUG_LOG(("StdLocalFileSystem::openFile - Error finding file %s\n", filename.string().c_str()));
					DEBUG_LOG(("StdLocalFileSystem::openFile - Got so far %s\n", pathCurrent.string().c_str()));	

					file->deleteInstance();
					return NULL;	
				}

				// Use the last known good path
				pathFixed = p;
			}
```

This is because the directory iterator above is checking file names and not the current path (of English vs english), so it's checking English vs EA_LOGO.BIK for example.

### PR DESCRIPTION
**Pull request by d10sfan**
Closes https://github.com/Fighter19/CnC_Generals_Zero_Hour/issues/55

The logic to handle case sensitivity wasn't working for loading the intro videos and the campaign videos. The deep path seemed to confuse it. This helps by using the fixed path for the directory search. I was able to see the intro videos and the campaign start videos with this fix.

### CODE REVIEW

File: GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp [hunk 1]
```diff
@@ -90,12 +90,16 @@ File * StdLocalFileSystem::openFile(const Char *filename, Int access /* = 0 */)
 			{
 				pathFixedPart = p;
 			}
+			else if (std::filesystem::exists(pathFixed / p, ec))
+			{
+				pathFixedPart = p;
+			}
```
Comment (d10sfan) [inline GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp:96]: This is mainly for the next loop to check that if the pathFixed exists, this is for when "Data/English/Movies" is accurate which is the path fixed plus p

File: GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp [hunk 2]
```diff
@@ -90,12 +90,16 @@ File * StdLocalFileSystem::openFile(const Char *filename, Int access /* = 0 */)
...
 			else
 			{
 				// Check if the subpath exists using case-insensitive comparison
-				for (auto& entry : std::filesystem::directory_iterator(pathCurrent, ec))
+				for (auto& entry : std::filesystem::directory_iterator(pathFixed, ec))
```
Comment (d10sfan) [inline GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp:100]: Using the fixed path to loop through, as otherwise it ends up not being correct inside the loop

File: GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp [hunk 3]
```diff
@@ -90,12 +90,16 @@ File * StdLocalFileSystem::openFile(const Char *filename, Int access /* = 0 */)
...
 				{
-					if (strcasecmp(entry.path().filename().string().c_str(), filename.string().c_str()) == 0)
+					if (strcasecmp(entry.path().filename().string().c_str(), p.string().c_str()) == 0)
```
Comment (d10sfan) [inline GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp:102]: Since we can have multiple levels checking the current path part (p) instead of the filename.
